---
title: "Getting Set Up With RStudio"
pkgdown:
  as_is: true
output: 
  rmarkdown::html_document:
    number_sections: true
    toc: true
vignette: >
  %\VignetteIndexEntry{Getting Set Up With RStudio}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,  include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
knitr::opts_chunk$set(fig.width=12, fig.height=8)
```

# Using RStudio on the VM

To run RStudio on your VM, follow the instructions on [this page](https://canvas.ox.ac.uk/courses/66998/pages/your-hds-virtual-machine/). 

In brief, log in to the VM, and run:

```{r, engine = 'bash', eval = FALSE}
module load rstudio/1.2.5033-fosscuda-2019b-Java-11
/apps/misc/rserver.sh
```

Then follow the on-screen instructions to set up an ssh tunnel by running something like the following locally (numbers and username may differ):

```{r, engine = 'bash', eval = FALSE}
ssh -L 8787:localhost:8787 username@vm.bmrc.ox.ac.uk # change the username and vm number
```

Finally, navigate to http://localhost:8787 in your browser. 

